name: Merge latest Tag from Upstream
on:
  schedule:
    - cron: '0 0 */2 * *'  # Run every 2 days
  workflow_dispatch:  # Allows manual trigger

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the local repo
        uses: actions/checkout@v4

      - name: Configure git to ignore changes in specific files
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          echo "README.md merge=ours" >> .gitattributes
          echo "LICENSES/* merge=ours" >> .gitattributes
          echo "workflows/* merge=ours" >> .gitattributes
          echo "LICENSE.md merge=ours" >> .gitattributes
          git add .gitattributes
          git commit -m "Set our merge strategy for specific files."

      - name: Fetch the upstream repo with tags
        run: git fetch --tags https://github.com/run-llama/create-llama.git  # Add the URL of the upstream repo here

      - name: Get the latest tag
        id: latest_tag
        run: echo "::set-output name=tag::$(git describe --tags `git rev-list --tags --max-count=1`)"


      - name: Merge latest tag 
        run: |
          git merge --allow-unrelated-histories -X theirs --no-commit ${{ steps.latest_tag.outputs.tag }}
          
          
      - name: Create new branch
        id: main_branch_name
        run: echo "::set-output name=main_branch::PR-Tag-${{ steps.latest_tag.outputs.tag }}"
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          commit-message: "Merge latest tag from upstream"
          branch: ${{ steps.main_branch_name.outputs.main_branch }}
          title: "Merge Latest Tag - ${{ steps.latest_tag.outputs.tag }} from Upstream"
          body: |
            This pull request merges the latest tag from the upstream repository.
            Please review and merge manually.
