name: test

on:
  schedule:
    - cron: '0 0 */2 * *'  # Run every 2 days
  workflow_dispatch:  # Allows manual trigger

jobs:
  merge-upstream:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the local repo
        uses: actions/checkout@v4

      - name: Configure git to ignore changes in specific files
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          echo "README.md merge=ours" >> .gitattributes
          echo "LICENSES/* merge=ours" >> .gitattributes
          echo "workflows/* merge=ours" >> .gitattributes
          echo "LICENSE.md merge=ours" >> .gitattributes
          git add .gitattributes
          git commit -m "Set our merge strategy for specific files."

      - name: Fetch the upstream repo with tags
        run: git fetch --tags https://github.com/run-llama/create-llama.git  # Add the URL of the upstream repo here

      - name: Get the latest tag
        id: latest_tag
        run: echo "::set-output name=tag::$(git describe --tags `git rev-list --tags --max-count=1`)"

      - name: Checkout the latest tag
        run: git checkout ${{ steps.latest_tag.outputs.tag }}

      - name: Generate branch name
        id: branch_name
        run: echo "::set-output name=branch::PR-Tag-${{ steps.latest_tag.outputs.tag }}"

      - name: Checkout main branch
        run: git checkout main

      - name: Create a new branch with the latest tag from upstream
        run: git checkout -b ${{ steps.branch_name.outputs.branch }}

      - name: Push the new branch to the repository
        run: git push origin ${{ steps.branch_name.outputs.branch }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          commit-message: "Merge latest tag from upstream"
          branch: ${{ steps.branch_name.outputs.branch }}
          title: "Merge Latest Tag - ${{ steps.latest_tag.outputs.tag }} from Upstream"
          body: |
            This pull request merges the latest tag from the upstream repository into the main branch.
            Please review and merge manually.
